#!/bin/sh
set -ue

hostname=`hostname -f`
mountpoint=`relation-get mountpoint`
fstype=`relation-get fstype`
options=`relation-get options`
remote_host=`relation-get hostname`
if [ -z "$remote_host" ] ; then
    ensemble-log "remote host not set yet."
    exit 0
fi

remote_ip=`dig +short $remote_host|head -n 1`

echo "NFS client test formula"
echo $remote_ip

local_mountpoint=`config-get local_mountpoint`
mkdir -p $local_mountpoint

local_owner=`config-get owner`
chown -f $owner $local_mountpoint

mount -t $fstype -o $options $remote_host:$mountpoint $local_mountpoint

