#!/bin/bash
set -ue

[[ -f "$(dirname $0)/config" ]] && source "$(dirname $0)/config" # goes away with config.yaml / config-get
local_mountpoint=${config_mountpoint:-"/opt/mount"} # `config-get mountpoint`

umount $local_mountpoint
[ $? -eq 0 ] || ensemble-log "umount failed: $local_mountpoint"

