#!/bin/bash
set -ue

remote_host=`relation-get hostname`
if [ -z "$remote_host" ] ; then
    ensemble-log "remote host not set yet."
    exit 0
fi
export_path=`relation-get mountpoint`
fstype=`relation-get fstype`

local_mountpoint=`config-get mountpoint`
local_owner=`config-get owner`

create_local_mountpoint() {
  ensemble-log "creating local mountpoint"
  umask 002
  mkdir -p $local_mountpoint
  # create owner if necessary?
  chown -f $local_owner.$local_owner $local_mountpoint
}
[ -d $local_mountpoint ] || create_local_mountpoint 

share_already_mounted() {
  # better way to do this?
  `mount | grep -q $local_mountpoint`
}
mount_share() {
  local retry=3
  while [ $retry -gt 0 ]; do
    ensemble-log "mounting nfs share"
    #options=""
    #mount -t $fstype -o $options $remote_host:$export_path $local_mountpoint
    mount -t $fstype $remote_host:$export_path $local_mountpoint
    [ $? -eq 0 ] || ensemble-log "mount failed: $local_mountpoint"

  done
}
share_already_mounted || mount_share 

